trigger:
  branches:
   include:
     - main

variables:
  source_branches: $(Build.SourceBranch)
  mid_var: "world"

jobs:
  - job: job_1
    pool:
      Default
    
    steps:
      - script: echo $(Build.SourceBranch)
        displayName: just print
        
      - script: echo $(source_branches)
        displayName: print self variable

      - script: echo "##vso[task.setvariable variable=mid_var]hello"
        displayName: set mid_var

      - script: |
          echo ${{ variables.mid_var }}
          echo $(mid_var)
        displayName: print mid_var
        
      - script: xorg
        displayName: failing pipeline
        
      - script: echo "hello world"
        displayName: continue on error

      - script: echo "hello world 2"
        displayName: continue on error 2 

  - job: job_2
    dependsOn: 
      - job_1
    
    pool:
      Default

    steps:
      - script: echo $(mid_var)
        displayName: print mid_var
        condition: and(eq($(target_branch), 'refs/heads/main'), failed())