trigger:

  branches:
   include:
     - main

variables:
  source_branches: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  mid_var: "world"

jobs:
  - job: job_1
    pool:
      Default
    
    steps:
      - script: echo $(Build.SourceBranch)
        displayName: just print
        
      - script: echo $(source_branches)
        displayName: print self variable

      - script: echo "##vso[task.setvariable variable=mid_var]hello"
        displayName: set mid_var

      - script: |
          echo ${{ variables.mid_var }}
          echo $(mid_var)
        displayName: print mid_var

  - job: job_2
    dependsOn: job_1
    
    condition: and(succeeded(), eq(variables.source_branches, true))

    pool:
      Default

    steps:
      - script: echo $(mid_var)
        displayName: print mid_var
      
      - task: UniversalPackages@0
        inputs:
          command: 'publish'
          publishDirectory: '/home/azureuser/publish'
          feedsToUsePublish: 'internal'
          vstsFeedPublish: 'a6c64c35-d43e-4093-b52a-fcf8df018d06/b4bcf7b5-7f24-41ff-a3f7-b818616b04ae'
          vstsFeedPackagePublish: 'my-first-package'
          versionOption: 'major'