trigger:
  branches:
   include:
     - main

variables:
  source_branches: $(Build.SourceBranch)
  mid_var: "world"

jobs:
  - job: job_1
    pool:
      Default
    
    steps:
      - script: echo $(Build.SourceBranch)
        displayName: just print
        
      - script: echo $(source_branches)
        displayName: print self variable

      - script: echo "##vso[task.taskVariable variable=mid_var]hello"
        displayName: set mid_var

      - script: |
          echo ${{ variables.mid_var }} 
          echo $(mid_var)
        displayName: print mid_var