pr:
  branches:
    include:
      - main

variables:
  target_branch: eq(variables['System.PullRequest.TargetBranch'], /refs/heads/main)

jobs:
  - job: job_1
    pool:
      vmImage: ubuntu-latest
    
    steps:
      - script: echo $(System.PullRequest.TargetBranch)
        displayName: just print target branch
      
      - script: echo $(target_branch)
        displayName: print value of variable