trigger:
  branches:
   include:
     - main

variables:
  source_branches: $(Build.SourceBranch)

jobs:
  - job: job_1
    pool:
      Default
    
    steps:
      - script: echo $(Build.SourceBranch)
        displayName: just print
        
      - script: echo $(source_branches)
        displayName: print self variable